### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by EmilStenstrom** [tdpetrou/RDF-Triple-API#1]
What language is this project licensed under? I was hoping something permissive like MIT, so I can improve it and release a new version myself.

**Comment by tdpetrou** [comment]
MIT license added. Feel free to take off and run with this. You also might want to check with the authors of the paper - not sure if there are patent issues.

**Comment by EmilStenstrom** [comment]
Thank you! Really appreciate your hard work! :)
